### ISSUE TITLE
[FEATURE]: 망할 lint/ github actions 수리....... 😭😭😭

### ISSUE THREAD

**Issue by tgyuuAn** [tgyuuAn/BaekyoungE#32]
### 작업 사항

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/7cd81059-1290-48cc-815c-01ee3bdc2121)

![image](https://github.com/tgyuuAn/BaekyoungE/assets/116813010/873e64e4-a3f6-4cba-acff-1b6081dd7814)

**그만해...!**

### Todo

- [ ] github actions 공부
- [ ] 수리..

### 기타사항

😱😱😱

**Comment by jeongjaino** [comment]
😙😙

**Comment by jeongjaino** [comment]
@tgyuuAn 

티지와이유유 와이 디든츄 에스크 포 미 ?

왓 이즈 디프런스 비트윈 와피 액션스 엔 백경이 액션스 

엣 와피 액션즈, 유 캔 시 댓 비로우 코드 

```yaml
      - name: Run ktlint
        run: ./gradlew ktlintCheck
```

잇 저스트 런 케이티 린트 온 유얼 프로젝트 그레들 

앤 잇 리즌 와이 위 캔 애드 케이티린트 그래들 온 프로젝트 ! 

쏘 

렛 미씨 백경이 액션스 

```yaml
 - name: ktlint
              uses: ScaCap/action-ktlint@master
              with:
                  github_token: ${{ secrets.github_token }}
                  reporter: github-pr-check
```

티지와이유유 유스 커스텀 깃헙 액션스, 낫 프로젝트 케이티린트 


아이노 아이노, 잇 쿠드 고잉투 런 웰 


밧뜨 하우에벌, 


커스텀 액션즈 케이티 린트 낫 코러스펀드 투 프로젝트 케이티린트 ?


오얼 


썸데이 이프 유 캔 커스텀 케이티린트 옵션즈 ?
